vis:map(vis.modes.NORMAL, "gx", function(keys)
    local handle = io.popen("xdg-open https://reddit.com")
    local data = handle:read()
    local success, msg, status = handle:close()
end, "Jump to URL")
